### PR TITLE
Refactored the code and Implemented some spring boot practices

### PR DESCRIPTION
**Pull request by rprakashg**
Implemented some spring boot features into incidents portion of the application
- Async Implementation
- Defined external properties in yml file and implemented type-safe configuration properties
- Docker support
- Changed from WAR to JAR packaging

### CODE REVIEW

**Comment by rprakashg** [comment]
Also structured the code based on spring boot recommended methods

**Comment by rsponholtz** [comment]
Any reason for removing the WAR packaging?  We left that in (from the Spring boot samples, btw) because we are deploying into an Azure Web App running Tomcat, and need to push the WAR file.  Of course, we could just deploy the Spring Boot application without any container, but we went the Tomcat route to show the hosted Tomcat mechanism in Azure.

**Comment by rprakashg** [comment]
Ok that makes sense, I can revert back, just have to uncomment in the gradle file and make following changes in Dockerfile

- Change base image to tomcat:8.0.20-jre8

- Copy ROOT.WAR file into /usr/local/tomcat/webapps/ folder

**Comment by rprakashg** [comment]
Also was thinking should add methods in controller that uses Service methods that leverages caching. That's what was happening earlier. I added async methods into Service components, probably should use Netflix Hystrix library here for  circuit breaker, thought I'll wire that up later

**Comment by rsponholtz** [comment]
We need to get the configuration variables from the OS environment.  That's how Azure supplies those configurations (that you put in the Azure portal) to the application.  So that's why those configurations weren't pulled from the yml file..  I attempted to use @ConfigurationProperties but that didn't work for me, so I just went for System.getenv().. Ugly but it works, but I'd love a better solution..

**Comment by rprakashg** [comment]
Ok then what I would do is add a method that returns Config properties class in ApplicationConfig class, annotate with @Bean, Autowire a private variable of type Environment class. in the method then load the values from Environment. I'll make the changes tonight

**Comment by rprakashg** [comment]
Benefit is you can Autowire config properties into anything that requires it, not have to pull it out of Environment variables all the time

**Comment by rprakashg** [comment]
Have u guys seen any issues dropping war into native tomcat container in Azure. Reason why I'm asking is that spring boot has tomcat built in 
Never ran it as war file in hosted tomcat before, was wondering

**Comment by rsponholtz** [comment]
It's nice to build & run the application at the command line simply with `gradle bootRun`, which includes the built-in tomcat.  But with `gradle war`, it generates the WAR file that you can just throw on the Tomcat server.  Works fine!  Of course, there are some considerations around the configuration, since the xml/yml files are baked into the WAR file.

**Comment by rprakashg** [comment]
Hey take a look at the updates. Still keeping configuration file in yml and typesafe classes that gets autowired, updated env.sh and env.bat file to pass parameters to bootRun which will set the JVM params when running the spring app. Also refactored the StorageClient moved into a service with Async methods

**Comment by rsponholtz** [comment]
I deleted those two files - they were really just for my use, and we don't use them in the hands-on-labs.

**Comment by rsponholtz** [comment]
I'll test the yml configuration - most importantly, we need the environment variables to override the yml configurations.  [The documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) seems to indicate that this should be the case.

**Comment by rprakashg** [comment]
Thats right I could have just referenced the environment variable directly in the yml for ex inside ${ environment variable} I'll modify the file

**Comment by rsponholtz** [comment]
I've actually never gotten a pull request on anything I've done in GitHub, so forgive me for working through this item by item.  Since this is pretty much my first Spring application, I'm glad to take suggestions.  However, since we've got several HOLs associated with this, changes to the first one need to be walked through the whole set of labs, as well as having the documentation updated, i.e. a lot of work!   Anyway, I like how you moved config into it's own package - I'm curious though, why did you consolidate configurations into one class? From the standpoint of modularity, I'd argue that it would be better to have a fooConfig.java for each major foo feature that we add to the system, as long as there isn't any interaction between them.  That would also make each more self- contained for each hands-on-lab.

**Comment by stevenfollis** [comment]
@rprakashg Hi Ram thanks for the PR! In the future please open an issue(s) so we can discuss approaches and features before PR's. Thanks!

**Pull request merged**
