### PR TITLE
Updating ReadMe with fixes

### PR DESCRIPTION
**Pull request by dhaval24**
This PR  Updates configuration code (needed to capture dependencies using Application Insights Java Agent) for initializing AI with Spring Boot, increasing the version of AI dependencies.

I will submit another PR for adding more information on how to capture dependencies with Application Insights Java Agent (i.e capture Oracle / MySQL/ MsSQL/ Redis calls automatically and show case on AppMap too!)
**Summary**

This PR fixes/implements the following **bugs/features**

* [ ] Bug 1
* [ ] Bug 2
* [ ] Feature 1
* [ ] Feature 2
* [ ] Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

This  updates the AI-SDK to latest version which would fix several blocking issues present in the SDK, and adds a mandatory App-Name as a parameter to WebRequestTrackingFilter during configuration which is required.

**Test plan (required)** 
N/A : ReadMe Changes

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

**Code formatting**

**Closing issues**

Fixes #

### CODE REVIEW

**Comment by dhaval24** [comment]
@IRRDC could you please review this PR and merge it. It has critical fixes for correctly configuring Application Insights with Spring-Boot.

**Comment by IRRDC** [comment]
Can you please explain why it is a critical fix to switch the working solution based on a stable API to a beta release?

**Comment by dhaval24** [comment]
@IRRDC apologies for a delayed response here, we have recently released the latest stable version of AI Java SDK and I have updated the PR to point to latest version on Maven Central.  I have also updated configuration code slightly, to remove hard coding of application name in the filter, to dynamically picking it from application.properties file and also ensuring that AI Filter gets the highest precedence. Please review and approve the changes.

**Comment by IRRDC** [comment]
@dhaval24 Please fix the following in your PR:
Line 75: You are mixing "compile group:..." with "compile(...)" commands. Is this intentional?
Line 115: Requires import org.springframework.core.Ordered; to be added to the file. This should be mentioned.
Line 121: Requires import org.springframework.beans.factory.annotation.Value; to be added to the file. This should be mentioned.
Line 121: webRequestTrackingFilter must be uppercase
Line 363: Should be 2.+ instead of 2.0.0-BETA too or not?
Compilation of the changed code fails with: Parameter 0 of method aiFilterRegistration in devCamp.WebApp.configurations.AppInsightsConfig required a bean of type 'com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter' that could not be found.

**Comment by dhaval24** [comment]
@IRRDC thanks for pointing out. I have updated the comments and changed the config code slightly. I tested locally and this complies perfectly fine. Regarding the comment on lower case, I think it's perfectly valid.

**Comment by IRRDC** [comment]
@dhaval24
There is a ; missing in line 94.
There is a ) missing in line 114.
And I still can't compile your code. When I copy it and fix the two typos I get two errors on line 114 regarding "@Value" which you could move to the signature of the method and use the value via a parameter like you do in WebRequestTrackingFilter.
I made those changes and added them to your PR. Please check them. If you confirm that they are correct I will merge the PR.

**Pull request merged**
